// <auto-generated />
namespace PickUpSports.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addskilllevelandplayerratingtoevent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addskilllevelandplayerratingtoevent));
        
        string IMigrationMetadata.Id
        {
            get { return "202001211724397_Add skilllevel and player rating to event"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
