// <auto-generated />
namespace PickUpSports.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addtimedateandmaxplayerstoevent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addtimedateandmaxplayerstoevent));
        
        string IMigrationMetadata.Id
        {
            get { return "202001212021565_Add time, date, and max players to event"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
